"""
Django settings for noska_hamster project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("ENVIRONMENT", "development") != "production"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-_7&v!j(qanh_v=6#a(g2(lc^c+olo2in=!h*+57gy-s-i-=%=u" if DEBUG else "")

# Production Host Configuration
if DEBUG:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", ".ngrok.app", ".ngrok-free.app", "*"]
else:
    # In production, only allow specifically defined hosts (e.g. your production domain)
    allowed = os.environ.get("ALLOWED_HOSTS", "")
    ALLOWED_HOSTS = [h.strip() for h in allowed.split(",")] if allowed else []

# Percayai origin Ngrok untuk form submission (Django Admin)
CSRF_TRUSTED_ORIGINS = ["https://*.ngrok-free.app", "https://*.ngrok.app"]
if not DEBUG and os.environ.get("FRONTEND_URL"):
    CSRF_TRUSTED_ORIGINS.append(os.environ.get("FRONTEND_URL"))


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "cloudinary",
    "cloudinary_storage",
    # Noska Hamster Apps
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "noska_hamster.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "noska_hamster.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL (Production) — ganti kredensial sesuai environment
# Untuk development tanpa PostgreSQL, gunakan SQLite di bawah.
# Kita kembali menggunakan SQLite karena data aman di Mac Anda.
DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=0,  # MUST BE 0 FOR SUPABASE SESSION POOLER!
        ssl_require=True if "supabase" in os.environ.get("DATABASE_URL", "") else False
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "id"

TIME_ZONE = "Asia/Jakarta"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User-uploaded: foto, video)
# Disimpan secara lokal di folder media/ (sebagai fallback)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# File Storage Configuration (Django 4.2+)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Cloudinary Setup untuk Auto-Optimization
if os.environ.get("CLOUDINARY_URL"):
    STORAGES["default"]["BACKEND"] = "cloudinary_storage.storage.MediaCloudinaryStorage"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ──────────────────────────────────────────────
# CORS Configuration
# ──────────────────────────────────────────────
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
if os.environ.get("FRONTEND_URL"):
    CORS_ALLOWED_ORIGINS.append(os.environ.get("FRONTEND_URL"))

# ──────────────────────────────────────────────
# Frontend Public URL (for customer-facing links)
# ──────────────────────────────────────────────
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

# ──────────────────────────────────────────────
# Komerce (RajaOngkir) Cek Ongkir API
# ──────────────────────────────────────────────
KOMERCE_API_KEY = os.environ.get("KOMERCE_API_KEY", "")

# ──────────────────────────────────────────────
# DOKU Payment Gateway (Jokul Checkout)
# ──────────────────────────────────────────────
DOKU_CLIENT_ID = os.environ.get("DOKU_CLIENT_ID", "") 
DOKU_SECRET_KEY = os.environ.get("DOKU_SECRET_KEY", "")
DOKU_BASE_URL = os.environ.get("DOKU_BASE_URL", "https://api-sandbox.doku.com")

# ──────────────────────────────────────────────
# Django REST Framework
# ──────────────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle"
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100000/day",
        "user": "100000/day",
        "login": "20/minute"
    }
}

# Increase upload limits for photos and videos
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# ──────────────────────────────────────────────
# Redis Cache Configuration
# ──────────────────────────────────────────────
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# ──────────────────────────────────────────────
# Celery Configuration
# ──────────────────────────────────────────────
CELERY_BROKER_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1")
CELERY_RESULT_BACKEND = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'check-expired-transactions-every-5-mins': {
        'task': 'core.tasks.check_pending_transactions',
        'schedule': crontab(minute='*/5'),
    },
}

