services:
  - type: web
    name: noska-hamster-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn noska_hamster.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: FRONTEND_URL
        sync: false
