# Generated by Django 6.0.4 on 2026-05-01 12:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nama_customer",
                    models.CharField(max_length=150, verbose_name="Nama Customer"),
                ),
                (
                    "nomor_wa",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Nomor WhatsApp"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("address_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "label_alamat",
                    models.CharField(
                        default="Rumah",
                        help_text="Contoh: Rumah, Kantor, Toko",
                        max_length=50,
                        verbose_name="Label",
                    ),
                ),
                (
                    "nama_penerima",
                    models.CharField(max_length=150, verbose_name="Nama Penerima"),
                ),
                (
                    "nomor_wa_penerima",
                    models.CharField(max_length=20, verbose_name="No. WA Penerima"),
                ),
                ("detail_alamat", models.TextField(verbose_name="Detail Alamat")),
                (
                    "kecamatan",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kecamatan"
                    ),
                ),
                (
                    "kota_kabupaten",
                    models.CharField(max_length=100, verbose_name="Kota / Kabupaten"),
                ),
                ("provinsi", models.CharField(max_length=100, verbose_name="Provinsi")),
                (
                    "kode_pos",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Kode Pos"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Alamat Utama?"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="core.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alamat",
                "verbose_name_plural": "Alamat",
                "db_table": "addresses",
            },
        ),
        migrations.CreateModel(
            name="MasterCourier",
            fields=[
                ("courier_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nama_kurir",
                    models.CharField(
                        help_text="Contoh: JNE, Grab Instant, Kurir Pribadi",
                        max_length=100,
                        verbose_name="Nama Kurir",
                    ),
                ),
                (
                    "jenis_layanan",
                    models.CharField(
                        help_text="Contoh: Same Day, Reguler, Cargo Hewan",
                        max_length=100,
                        verbose_name="Jenis Layanan",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif?")),
            ],
            options={
                "verbose_name": "Kurir",
                "verbose_name_plural": "Kurir",
                "db_table": "master_couriers",
                "unique_together": {("nama_kurir", "jenis_layanan")},
            },
        ),
        migrations.CreateModel(
            name="MasterVariant",
            fields=[
                ("variant_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "spesies",
                    models.CharField(
                        help_text="Contoh: Syrian, Campbell, Winter White",
                        max_length=100,
                        verbose_name="Spesies",
                    ),
                ),
                (
                    "varian_warna",
                    models.CharField(
                        help_text="Contoh: Golden, Black Bear, Sapphire",
                        max_length=100,
                        verbose_name="Varian Warna",
                    ),
                ),
                (
                    "jenis_bulu",
                    models.CharField(
                        default="Short Hair",
                        help_text="Contoh: Short Hair, Long Hair, Satin, Rex",
                        max_length=50,
                        verbose_name="Jenis Bulu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master Varian",
                "verbose_name_plural": "Master Varian",
                "db_table": "master_variants",
                "ordering": ["spesies", "varian_warna"],
                "unique_together": {("spesies", "varian_warna", "jenis_bulu")},
            },
        ),
        migrations.CreateModel(
            name="LiveInventory",
            fields=[
                ("inventory_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "kode_hamster",
                    models.CharField(
                        blank=True,
                        help_text="Kode unik per individu, misal: SYR-GB-001",
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="Kode Hamster",
                    ),
                ),
                (
                    "tanggal_sesi_live",
                    models.DateField(verbose_name="Tanggal Sesi Live"),
                ),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[
                            ("Jantan", "Jantan"),
                            ("Betina", "Betina"),
                            ("Belum Diketahui", "Belum Diketahui"),
                        ],
                        default="Belum Diketahui",
                        max_length=20,
                        verbose_name="Jenis Kelamin",
                    ),
                ),
                (
                    "usia_bulan",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Usia (bulan)",
                    ),
                ),
                (
                    "grade_corak",
                    models.CharField(
                        blank=True,
                        help_text="Contoh: A+, A, B+, B",
                        max_length=20,
                        verbose_name="Grade Corak",
                    ),
                ),
                (
                    "kondisi_fisik",
                    models.TextField(
                        blank=True,
                        help_text="Catatan kondisi: sehat, cacat ringan, dll.",
                        verbose_name="Kondisi Fisik",
                    ),
                ),
                (
                    "url_foto",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL Foto"
                    ),
                ),
                (
                    "url_video",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL Video"
                    ),
                ),
                (
                    "harga_display",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Harga Display (Rp)",
                    ),
                ),
                (
                    "status_ketersediaan",
                    models.CharField(
                        choices=[
                            ("Tersedia", "Tersedia"),
                            ("Terjual", "Terjual"),
                            ("Hold", "Hold"),
                        ],
                        default="Tersedia",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="live_items",
                        to="core.mastervariant",
                        verbose_name="Varian Genetik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Live Inventory",
                "verbose_name_plural": "Live Inventory",
                "db_table": "live_inventory",
                "ordering": ["-tanggal_sesi_live", "status_ketersediaan"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nomor_invoice",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="No. Invoice",
                    ),
                ),
                (
                    "tanggal_order",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Order"
                    ),
                ),
                (
                    "jenis_penjualan",
                    models.CharField(
                        choices=[
                            ("Live", "Live (Eceran Eksklusif)"),
                            ("Grosir", "Grosir (Masal)"),
                        ],
                        max_length=10,
                        verbose_name="Jenis Penjualan",
                    ),
                ),
                (
                    "status_order",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Packing", "Packing"),
                            ("Shipped", "Shipped"),
                            ("Delivered", "Delivered"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                        verbose_name="Status Order",
                    ),
                ),
                (
                    "total_order",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Total Order (Rp)",
                    ),
                ),
                (
                    "catatan_order",
                    models.TextField(blank=True, verbose_name="Catatan Order"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="core.address",
                        verbose_name="Alamat Pengiriman",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="core.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "orders",
                "ordering": ["-tanggal_order"],
            },
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                ("ledger_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tanggal_transaksi",
                    models.DateField(verbose_name="Tanggal Transaksi"),
                ),
                (
                    "tipe_arus",
                    models.CharField(
                        choices=[("Masuk", "Pemasukan"), ("Keluar", "Pengeluaran")],
                        max_length=10,
                        verbose_name="Tipe Arus",
                    ),
                ),
                (
                    "kategori_dana",
                    models.CharField(
                        choices=[
                            ("Penjualan Live", "Penjualan Live"),
                            ("Penjualan Grosir", "Penjualan Grosir"),
                            ("Ongkir", "Ongkir"),
                            ("Pakan", "Pakan"),
                            ("Kandang & Peralatan", "Kandang & Peralatan"),
                            ("Kesehatan", "Kesehatan"),
                            ("Operasional", "Operasional"),
                            ("Lainnya", "Lainnya"),
                        ],
                        max_length=30,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "nominal",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Nominal (Rp)",
                    ),
                ),
                ("keterangan", models.TextField(blank=True, verbose_name="Keterangan")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kosongkan untuk pengeluaran bebas.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="core.order",
                        verbose_name="Order Terkait",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buku Kas",
                "verbose_name_plural": "Buku Kas",
                "db_table": "ledger",
                "ordering": ["-tanggal_transaksi", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "order_detail_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "qty",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Qty",
                    ),
                ),
                (
                    "harga_satuan_deal",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="Harga Satuan Deal (Rp)",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        editable=False,
                        max_digits=15,
                        verbose_name="Subtotal (Rp)",
                    ),
                ),
                (
                    "catatan_khusus",
                    models.TextField(blank=True, verbose_name="Catatan Khusus"),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Isi untuk penjualan LIVE (qty otomatis 1).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_details",
                        to="core.liveinventory",
                        verbose_name="Live Inventory Item",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="core.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Isi untuk penjualan GROSIR.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_details",
                        to="core.mastervariant",
                        verbose_name="Varian (Grosir)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detail Order",
                "verbose_name_plural": "Detail Order",
                "db_table": "order_details",
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("shipment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nomor_resi",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nomor Resi"
                    ),
                ),
                (
                    "tanggal_kirim",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Kirim"
                    ),
                ),
                (
                    "estimasi_hari",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Estimasi Hari"
                    ),
                ),
                (
                    "tanggal_diterima",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Diterima"
                    ),
                ),
                (
                    "status_kirim",
                    models.CharField(
                        choices=[
                            ("Menunggu Pickup", "Menunggu Pickup"),
                            ("Dalam Perjalanan", "Dalam Perjalanan"),
                            ("Sampai", "Sampai"),
                            ("Gagal", "Gagal"),
                        ],
                        default="Menunggu Pickup",
                        max_length=30,
                        verbose_name="Status Kirim",
                    ),
                ),
                (
                    "kondisi_hamster",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Sehat", "Sehat"),
                            ("Stres Ringan", "Stres Ringan"),
                            ("Cedera", "Cedera"),
                            ("Mati (DOA)", "Mati (DOA)"),
                        ],
                        max_length=30,
                        verbose_name="Kondisi Hamster Saat Tiba",
                    ),
                ),
                (
                    "catatan_pengiriman",
                    models.TextField(blank=True, verbose_name="Catatan Pengiriman"),
                ),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="core.mastercourier",
                        verbose_name="Kurir",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="core.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengiriman",
                "verbose_name_plural": "Pengiriman",
                "db_table": "shipments",
                "ordering": ["-tanggal_kirim"],
            },
        ),
    ]
