# Generated by Django 6.0.4 on 2026-05-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mastervariant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="liveinventory",
            name="box_kontainer",
            field=models.CharField(
                choices=[
                    ("A", "Box A"),
                    ("B", "Box B"),
                    ("C", "Box C"),
                    ("D", "Box D"),
                ],
                default="A",
                max_length=5,
                verbose_name="Box Kontainer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mastervariant",
            name="is_satin",
            field=models.BooleanField(default=False, verbose_name="Satin?"),
        ),
        migrations.AlterField(
            model_name="liveinventory",
            name="grade_corak",
            field=models.CharField(
                choices=[("S+", "S+"), ("A", "A"), ("B", "B"), ("C", "C")],
                max_length=5,
                verbose_name="Grade Corak",
            ),
        ),
        migrations.AlterField(
            model_name="liveinventory",
            name="kode_hamster",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto-generated: HAM-[Box]-[Urutan]",
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Kode Hamster",
            ),
        ),
        migrations.AlterField(
            model_name="liveinventory",
            name="usia_bulan",
            field=models.DecimalField(
                choices=[
                    ("1.0", "1.0 Bulan"),
                    ("1.5", "1.5 Bulan"),
                    ("2.0", "2.0 Bulan"),
                    ("2.5", "2.5 Bulan"),
                    ("3.0", "3.0 Bulan"),
                    ("3.5", "3.5 Bulan"),
                    ("4.0", "4.0 Bulan"),
                    ("4.5", "4.5 Bulan"),
                    ("5.0", "5.0 Bulan"),
                    ("5.5", "5.5 Bulan"),
                    ("6.0", "6.0 Bulan"),
                ],
                decimal_places=1,
                max_digits=3,
                verbose_name="Usia (bulan)",
            ),
        ),
        migrations.AlterField(
            model_name="mastervariant",
            name="jenis_bulu",
            field=models.CharField(
                choices=[
                    ("Short Hair", "Short Hair"),
                    ("Medium Hair", "Medium Hair"),
                    ("Long Hair", "Long Hair"),
                    ("Rex", "Rex"),
                ],
                default="Short Hair",
                max_length=50,
                verbose_name="Jenis Bulu",
            ),
        ),
        migrations.AlterField(
            model_name="mastervariant",
            name="spesies",
            field=models.CharField(
                choices=[
                    ("Syrian", "Syrian"),
                    ("Winter White", "Winter White"),
                    ("Campbell", "Campbell"),
                    ("Roborovski", "Roborovski"),
                ],
                max_length=100,
                verbose_name="Spesies",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mastervariant",
            unique_together={("spesies", "varian_warna", "jenis_bulu", "is_satin")},
        ),
    ]
