# Generated by Django 6.0.4 on 2026-05-02 08:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_mastervariant_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liveinventory",
            name="url_foto",
        ),
        migrations.RemoveField(
            model_name="liveinventory",
            name="url_video",
        ),
        migrations.AddField(
            model_name="liveinventory",
            name="foto_preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="inventory/foto/",
                verbose_name="Foto Preview",
            ),
        ),
        migrations.AddField(
            model_name="liveinventory",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="inventory/video/",
                verbose_name="Video Hamster",
            ),
        ),
        migrations.AlterField(
            model_name="liveinventory",
            name="usia_bulan",
            field=models.DecimalField(
                choices=[
                    (Decimal("1.0"), "1.0 Bulan"),
                    (Decimal("1.5"), "1.5 Bulan"),
                    (Decimal("2.0"), "2.0 Bulan"),
                    (Decimal("2.5"), "2.5 Bulan"),
                    (Decimal("3.0"), "3.0 Bulan"),
                    (Decimal("3.5"), "3.5 Bulan"),
                    (Decimal("4.0"), "4.0 Bulan"),
                    (Decimal("4.5"), "4.5 Bulan"),
                    (Decimal("5.0"), "5.0 Bulan"),
                    (Decimal("5.5"), "5.5 Bulan"),
                    (Decimal("6.0"), "6.0 Bulan"),
                ],
                decimal_places=1,
                max_digits=3,
                verbose_name="Usia (bulan)",
            ),
        ),
    ]
