# Generated by Django 6.0.4 on 2026-05-03 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_liveinventory_url_foto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                ("box_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nama_box",
                    models.CharField(
                        help_text="Contoh: Box A, Box B",
                        max_length=50,
                        verbose_name="Nama Box",
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        blank=True,
                        help_text="Contoh: Syrian Betina Siapan, Campbell Mixed",
                        max_length=150,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "urutan",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Urutan Tampil"
                    ),
                ),
            ],
            options={
                "verbose_name": "Box",
                "verbose_name_plural": "Boxes",
                "db_table": "boxes",
                "ordering": ["urutan", "nama_box"],
            },
        ),
        migrations.CreateModel(
            name="SetupSession",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nama_sesi",
                    models.CharField(
                        help_text="Contoh: Sesi Live 3 Mei 2026",
                        max_length=150,
                        verbose_name="Nama Sesi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Sesi Aktif?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sesi Live",
                "verbose_name_plural": "Sesi Live",
                "db_table": "setup_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="liveinventory",
            options={
                "ordering": ["box__urutan", "status_ketersediaan"],
                "verbose_name": "Live Inventory",
                "verbose_name_plural": "Live Inventory",
            },
        ),
        migrations.RemoveField(
            model_name="liveinventory",
            name="box_kontainer",
        ),
        migrations.RemoveField(
            model_name="liveinventory",
            name="tanggal_sesi_live",
        ),
        migrations.AddField(
            model_name="liveinventory",
            name="box",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.box",
                verbose_name="Box",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="box",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boxes",
                to="core.setupsession",
                verbose_name="Sesi",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="box",
            unique_together={("session", "nama_box")},
        ),
    ]
