# Generated by Django 6.0.4 on 2026-05-03 13:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_box_setupsession_alter_liveinventory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveinventory",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.models.get_video_storage,
                upload_to="inventory/video/",
                verbose_name="Video Hamster",
            ),
        ),
    ]
