# Generated by Django 6.0.4 on 2026-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_liveinventory_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="jenis_kelamin_box",
            field=models.CharField(
                blank=True,
                choices=[("Jantan", "Jantan"), ("Betina", "Betina"), ("Mix", "Mix")],
                max_length=50,
                null=True,
                verbose_name="Jenis Kelamin",
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="kategori_box",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Siapan", "Siapan"),
                    ("Anakan", "Anakan"),
                    ("Indukan", "Indukan"),
                    ("Mix", "Mix"),
                ],
                max_length=50,
                null=True,
                verbose_name="Kategori Box",
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="spesies",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Syrian", "Syrian"),
                    ("Campbell", "Campbell"),
                    ("Winter White", "Winter White"),
                    ("Roborovski", "Roborovski"),
                    ("Mix", "Mix"),
                ],
                max_length=50,
                null=True,
                verbose_name="Spesies",
            ),
        ),
        migrations.AlterField(
            model_name="box",
            name="kategori",
            field=models.CharField(
                blank=True,
                help_text="Field lama. Akan diabaikan jika field Spesies & Kategori baru diisi.",
                max_length=150,
                verbose_name="Kategori (Legacy)",
            ),
        ),
    ]
