# Generated by Django 6.0.4 on 2026-05-07 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_box_jenis_kelamin_box_box_kategori_box_box_spesies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="kelurahan_desa",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Kelurahan / Desa"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="nama_customer",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nama Customer"
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status_pembayaran",
                    models.CharField(
                        help_text="LUNAS, DP, BELUM LUNAS",
                        max_length=50,
                        verbose_name="Status Bayar",
                    ),
                ),
                (
                    "metode_pembayaran",
                    models.CharField(
                        blank=True,
                        help_text="BCA, QRIS, dll",
                        max_length=50,
                        verbose_name="Metode",
                    ),
                ),
                (
                    "total_bayar",
                    models.IntegerField(default=0, verbose_name="Total Bayar"),
                ),
                (
                    "keterangan_kurir",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Pengiriman"
                    ),
                ),
                (
                    "raw_rekapan",
                    models.TextField(blank=True, verbose_name="Teks Rekapan Asli"),
                ),
                (
                    "token_alamat",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Token Alamat",
                    ),
                ),
                (
                    "alamat_lengkap",
                    models.BooleanField(
                        default=False, verbose_name="Alamat Sudah Lengkap?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alamat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaksi",
                        to="core.address",
                        verbose_name="Alamat Pengiriman",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "hamsters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="transaksi",
                        to="core.liveinventory",
                        verbose_name="Hamster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaksi",
                "verbose_name_plural": "Transaksi",
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
