# Generated by Django 6.0.4 on 2026-05-07 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_address_kelurahan_desa_alter_customer_nama_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="core.customer",
                verbose_name="Customer",
            ),
        ),
    ]
