# Generated by Django 6.0.4 on 2026-05-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_transaction_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="biaya_ongkir",
            field=models.PositiveIntegerField(default=0, verbose_name="Biaya Ongkir"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="biaya_packing",
            field=models.PositiveIntegerField(default=0, verbose_name="Biaya Packing"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="metode_pembayaran",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Metode Pembayaran"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status_pembayaran",
            field=models.CharField(
                help_text="LUNAS, PENDING, DP",
                max_length=50,
                verbose_name="Status Bayar",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="total_bayar",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total Bayar (Hamster + Packing + Ongkir)"
            ),
        ),
    ]
