# Generated by Django 6.0.4 on 2026-05-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_transaction_biaya_ongkir_transaction_biaya_packing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mastercourier",
            name="estimasi_default_hari",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Otomatis terisi saat kalkulator invoice. Contoh: 1",
                null=True,
                verbose_name="Estimasi Default (Hari)",
            ),
        ),
        migrations.AlterField(
            model_name="mastercourier",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AlterField(
            model_name="mastercourier",
            name="jenis_layanan",
            field=models.CharField(
                blank=True,
                help_text="Contoh: ONS, REG, VIP, dll",
                max_length=100,
                verbose_name="Jenis Layanan",
            ),
        ),
        migrations.AlterField(
            model_name="mastercourier",
            name="nama_kurir",
            field=models.CharField(
                help_text="Contoh: TIKI, KIB, Karyati, dll",
                max_length=100,
                verbose_name="Nama Kurir/Ekspedisi",
            ),
        ),
    ]
