# Generated by Django 6.0.4 on 2026-05-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_mastercourier_estimasi_default_hari_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="nominal_dp",
            field=models.PositiveIntegerField(default=0, verbose_name="Nominal DP"),
        ),
    ]
