# Generated by Django 6.0.4 on 2026-05-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_transaction_nominal_dp"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="nomor_resi",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nomor Resi"
            ),
        ),
    ]
