# Generated by Django 6.0.4 on 2026-05-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_transaction_nomor_resi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status_pembayaran",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("BELUM LUNAS", "Belum Lunas"),
                    ("DP", "DP"),
                    ("LUNAS", "Lunas"),
                    ("CANCELLED", "Dibatalkan"),
                    ("DIKIRIM", "Dikirim"),
                    ("SAMPAI", "Sampai (Selesai)"),
                    ("GARANSI", "Garansi (Ada Masalah)"),
                ],
                default="PENDING",
                max_length=50,
                verbose_name="Status Bayar",
            ),
        ),
    ]
