# Generated by Django 6.0.4 on 2026-05-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_transaction_status_pembayaran"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="nominal_refund",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nominal Refund (Garansi)"
            ),
        ),
    ]
