# Generated by Django 6.0.4 on 2026-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_transaction_nominal_refund"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="tanggal_kirim",
            field=models.DateField(blank=True, null=True, verbose_name="Tanggal Kirim"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status_pembayaran",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("BELUM LUNAS", "Belum Lunas"),
                    ("DP", "DP"),
                    ("LUNAS", "Lunas"),
                    ("CANCELLED", "Dibatalkan"),
                    ("DIKIRIM", "Dikirim"),
                    ("SAMPAI", "Sampai (Selesai)"),
                    ("GARANSI", "Garansi (Ada Masalah)"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=50,
                verbose_name="Status Bayar",
            ),
        ),
    ]
