# Generated by Django 6.0.4 on 2026-05-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_transaction_tanggal_kirim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="hamsters_mati",
            field=models.TextField(
                blank=True, null=True, verbose_name="Hamster Bermasalah"
            ),
        ),
    ]
