# Generated by Django 6.0.4 on 2026-05-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_transaction_hamsters_mati"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="orderdetail",
            name="order",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderdetail",
            name="inventory",
        ),
        migrations.RemoveField(
            model_name="orderdetail",
            name="variant",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="courier",
        ),
        migrations.DeleteModel(
            name="Ledger",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderDetail",
        ),
        migrations.DeleteModel(
            name="Shipment",
        ),
    ]
