# Generated by Django 6.0.4 on 2026-05-15 10:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_order_address_remove_order_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="spesies",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Syrian", "Syrian"),
                    ("Campbell", "Campbell"),
                    ("Winter White", "Winter White"),
                    ("Roborovski", "Roborovski"),
                    ("Mix", "Mix"),
                    ("Perlengkapan Hamster", "Perlengkapan Hamster"),
                ],
                max_length=50,
                null=True,
                verbose_name="Spesies",
            ),
        ),
        migrations.AlterField(
            model_name="liveinventory",
            name="grade_corak",
            field=models.CharField(
                blank=True,
                choices=[("S+", "S+"), ("A", "A"), ("B", "B"), ("C", "C")],
                max_length=5,
                null=True,
                verbose_name="Grade Corak",
            ),
        ),
        migrations.AlterField(
            model_name="liveinventory",
            name="usia_bulan",
            field=models.DecimalField(
                blank=True,
                choices=[
                    (Decimal("1.0"), "1.0 Bulan"),
                    (Decimal("1.5"), "1.5 Bulan"),
                    (Decimal("2.0"), "2.0 Bulan"),
                    (Decimal("2.5"), "2.5 Bulan"),
                    (Decimal("3.0"), "3.0 Bulan"),
                    (Decimal("3.5"), "3.5 Bulan"),
                    (Decimal("4.0"), "4.0 Bulan"),
                    (Decimal("4.5"), "4.5 Bulan"),
                    (Decimal("5.0"), "5.0 Bulan"),
                    (Decimal("5.5"), "5.5 Bulan"),
                    (Decimal("6.0"), "6.0 Bulan"),
                ],
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Usia (bulan)",
            ),
        ),
        migrations.AlterField(
            model_name="mastervariant",
            name="jenis_bulu",
            field=models.CharField(
                choices=[
                    ("Short Hair", "Short Hair"),
                    ("Medium Hair", "Medium Hair"),
                    ("Long Hair", "Long Hair"),
                    ("Rex", "Rex"),
                    ("Tidak Ada", "Tidak Ada (Aksesoris)"),
                ],
                default="Short Hair",
                max_length=50,
                verbose_name="Jenis Bulu",
            ),
        ),
        migrations.AlterField(
            model_name="mastervariant",
            name="spesies",
            field=models.CharField(
                choices=[
                    ("Syrian", "Syrian"),
                    ("Winter White", "Winter White"),
                    ("Campbell", "Campbell"),
                    ("Roborovski", "Roborovski"),
                    ("Perlengkapan Hamster", "Perlengkapan Hamster"),
                ],
                max_length=100,
                verbose_name="Spesies",
            ),
        ),
    ]
