# Generated by Django 6.0.4 on 2026-05-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_box_spesies_alter_liveinventory_grade_corak_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="spesies",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Syrian", "Syrian"),
                    ("Campbell", "Campbell"),
                    ("Winter White", "Winter White"),
                    ("Roborovski", "Roborovski"),
                    ("Mix", "Mix"),
                    ("Perlengkapan", "Perlengkapan"),
                ],
                max_length=50,
                null=True,
                verbose_name="Spesies",
            ),
        ),
        migrations.AlterField(
            model_name="mastervariant",
            name="spesies",
            field=models.CharField(
                choices=[
                    ("Syrian", "Syrian"),
                    ("Winter White", "Winter White"),
                    ("Campbell", "Campbell"),
                    ("Roborovski", "Roborovski"),
                    ("Perlengkapan", "Perlengkapan"),
                ],
                max_length=100,
                verbose_name="Spesies",
            ),
        ),
    ]
