# Generated by Django 6.0.4 on 2026-05-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_box_spesies_alter_mastervariant_spesies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveinventory",
            name="status_ketersediaan",
            field=models.CharField(
                choices=[
                    ("Tersedia", "Tersedia"),
                    ("Terjual", "Terjual"),
                    ("Hold", "Hold"),
                    ("Disembunyikan", "Disembunyikan"),
                ],
                default="Tersedia",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
