# Generated by Django 6.0.4 on 2026-05-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_add_disembunyikan_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="alasan_batal",
            field=models.TextField(
                blank=True, null=True, verbose_name="Alasan Pembatalan"
            ),
        ),
    ]
