# Generated by Django 6.0.4 on 2026-05-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_transaction_alasan_batal"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="sudah_video_packing",
            field=models.BooleanField(
                default=False, verbose_name="Sudah Video Packing"
            ),
        ),
    ]
