# Generated by Django 6.0.4 on 2026-06-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_customer_user_alter_customer_nomor_wa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to="core.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Keranjang",
                "verbose_name_plural": "Keranjang",
                "db_table": "carts",
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_room",
                        to="core.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ruang Chat",
                "verbose_name_plural": "Ruang Chat",
                "db_table": "chat_rooms",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_is_admin",
                    models.BooleanField(
                        default=False, verbose_name="Kirim dari Admin?"
                    ),
                ),
                ("message", models.TextField(verbose_name="Pesan")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Sudah Dibaca?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.chatroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pesan Chat",
                "verbose_name_plural": "Pesan Chat",
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.cart",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.liveinventory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Keranjang",
                "verbose_name_plural": "Item Keranjang",
                "db_table": "cart_items",
                "unique_together": {("cart", "inventory")},
            },
        ),
    ]
