# Generated by Django 6.0.4 on 2026-06-02 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_cart_chatroom_chatmessage_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="related_inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_mentions",
                to="core.liveinventory",
                verbose_name="Terkait Produk",
            ),
        ),
    ]
