# Generated by Django 6.0.4 on 2026-06-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_chatmessage_related_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="destination_id",
            field=models.CharField(
                blank=True,
                help_text="ID Kelurahan dari RajaOngkir untuk kalkulasi ongkir",
                max_length=20,
                verbose_name="Destination ID (Ongkir)",
            ),
        ),
    ]
