# Generated by Django 6.0.4 on 2026-06-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_address_destination_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="doku_token",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="DOKU Token"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="DOKU Payment URL"
            ),
        ),
    ]
