# Generated by Django 6.0.4 on 2026-06-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_transaction_doku_token_transaction_payment_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("expense_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tanggal",
                    models.DateField(auto_now_add=True, verbose_name="Tanggal"),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("Pakan", "Pakan"),
                            ("Serbuk/Bedding", "Serbuk/Bedding"),
                            ("Vitamin/Obat", "Vitamin/Obat"),
                            ("Kardus/Packing", "Kardus/Packing"),
                            ("Lain-lain", "Lain-lain"),
                        ],
                        default="Lain-lain",
                        max_length=50,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "keterangan",
                    models.CharField(
                        help_text="Contoh: Beli pelet 10kg",
                        max_length=200,
                        verbose_name="Keterangan",
                    ),
                ),
                (
                    "nominal",
                    models.PositiveIntegerField(default=0, verbose_name="Nominal (Rp)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pengeluaran",
                "verbose_name_plural": "Pengeluaran",
                "db_table": "expenses",
                "ordering": ["-tanggal", "-created_at"],
            },
        ),
    ]
