# Generated by Django 6.0.4 on 2026-06-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_expense"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mastervariant",
            unique_together={("spesies", "varian_warna")},
        ),
        migrations.AddField(
            model_name="liveinventory",
            name="is_satin",
            field=models.BooleanField(default=False, verbose_name="Satin?"),
        ),
        migrations.AddField(
            model_name="liveinventory",
            name="jenis_bulu",
            field=models.CharField(
                choices=[
                    ("Short Hair", "Short Hair"),
                    ("Medium Hair", "Medium Hair"),
                    ("Long Hair", "Long Hair"),
                    ("Rex", "Rex"),
                    ("Tidak Ada", "Tidak Ada (Aksesoris)"),
                ],
                default="Short Hair",
                max_length=50,
                verbose_name="Jenis Bulu",
            ),
        ),
        migrations.RemoveField(
            model_name="mastervariant",
            name="is_satin",
        ),
        migrations.RemoveField(
            model_name="mastervariant",
            name="jenis_bulu",
        ),
    ]
