# Generated by Django 6.0.4 on 2026-06-09 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_mastervariant_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="tanggal",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Tanggal"
            ),
        ),
    ]
