# Generated by Django 6.0.4 on 2026-06-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_expense_tanggal"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="media_type",
            field=models.CharField(
                blank=True,
                help_text="image atau video",
                max_length=20,
                null=True,
                verbose_name="Tipe Media",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="media_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL Media"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="bukti_refund",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Bukti Refund"
            ),
        ),
    ]
